name: Deploy to Vercel

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */8 * * *"  # Runs every 8 hours
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "vercel-deploy"
  cancel-in-progress: true

env:
  BUILD_PATH: "."
  NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
  DISQUS_SHORTNAME: ${{ secrets.DISQUS_SHORTNAME }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build the project
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DISQUS_SHORTNAME: ${{ secrets.DISQUS_SHORTNAME }}
        run: |
          echo "NOTION_API_SECRET = $NOTION_API_SECRET"
          echo "DISQUS_SHORTNAME = $DISQUS_SHORTNAME"
          npx --no-install astro build
          npx --no-install pagefind --site dist
        working-directory: ${{ env.BUILD_PATH }}

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{ env.BUILD_PATH }}

  trigger_vercel:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4c6XMs3WQ74YQ9CTrDnoQ0RDWm40/hQqEjlS1aL